"""Initial definition

Revision ID: 0b04545ab0a3
Revises: 
Create Date: 2025-11-18 01:00:00.557581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b04545ab0a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(precision=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate')
    # ### end Alembic commands ###
